# Generated by Django 5.1.1 on 2024-10-28 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0002_mercadolivread'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mercadolivread',
            name='titulo',
            field=models.CharField(max_length=60),
        ),
    ]
