# Generated by Django 5.1.1 on 2024-10-28 12:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0003_alter_mercadolivread_titulo'),
    ]

    operations = [
        migrations.AddField(
            model_name='mercadolivread',
            name='atualizado_em',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='mercadolivread',
            name='produto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='anuncios', to='estoque.produto'),
        ),
    ]
