# Generated by Django 5.1.1 on 2024-10-28 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0004_mercadolivread_atualizado_em_mercadolivread_produto'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MercadoLivreAd',
        ),
    ]
