# Generated by Django 5.1.1 on 2024-10-28 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0008_mercadolivread'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MercadoLivreAd',
        ),
    ]
