# Generated by Django 5.1.1 on 2024-10-28 12:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0011_delete_mercadolivread'),
    ]

    operations = [
        migrations.CreateModel(
            name='MercadoLivreAd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mlb_id', models.CharField(max_length=50, unique=True)),
                ('titulo', models.CharField(max_length=60)),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantidade', models.IntegerField()),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('produto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='anuncios', to='estoque.produto')),
            ],
        ),
    ]
