# Generated by Django 5.1.1 on 2024-11-01 00:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0012_mercadolivread'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mercadolivread',
            name='atualizado_em',
        ),
        migrations.RemoveField(
            model_name='mercadolivread',
            name='preco',
        ),
        migrations.RemoveField(
            model_name='mercadolivread',
            name='quantidade',
        ),
        migrations.RemoveField(
            model_name='mercadolivread',
            name='titulo',
        ),
    ]
